import io.vertx.core.AbstractVerticle;
import io.vertx.core.http.HttpServer;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class DemoVerticle extends AbstractVerticle {


    private HttpServer server;

    public void start() {
        server = vertx.createHttpServer().requestHandler( request -> {
            request.response().putHeader("content-type","text/plain").end("hello world");
        });

        server.listen(8080);
    }


}
